/**
 * Declarative map of every editable BrandConfig path → how the inspector
 * renders it. Co-located with the schema so drift is caught: the content
 * surface is generated by walking DEFAULT_CONTENT (the full ContentMap), and
 * registry.test.ts walks it the same way — a new content field fails the
 * coverage test until it appears here. Overrides/palette/assets are curated.
 */
import type { ContentMap } from '../config/schema'
import { DEFAULT_CONTENT, PALETTES } from '../config/defaults'

export type FieldKind =
  | 'mode'
  | 'color'
  | 'text'
  | 'textarea'
  | 'select'
  | 'number'
  | 'range'
  | 'list'
  | 'asset'
  | 'toneMap'

export interface FieldDef {
  path: string
  label: string
  kind: FieldKind
  group: string
  options?: string[]
  min?: number
  max?: number
  step?: number
}

export interface GroupDef {
  id: string
  label: string
  scope: 'page' | 'global' | 'assets'
  route?: string
}

export const GROUPS: readonly GroupDef[] = [
  { id: 'theme', label: 'Theme', scope: 'global' },
  { id: 'brand', label: 'Brand & Wordmark', scope: 'global' },
  { id: 'palette', label: 'Palette', scope: 'global' },
  { id: 'shape', label: 'Shape & Type', scope: 'global' },
  { id: 'nav', label: 'Navigation', scope: 'global' },
  { id: 'footer', label: 'Footer', scope: 'global' },
  { id: 'onboarding', label: 'Onboarding', scope: 'page', route: '/onboarding' },
  { id: 'missions', label: 'Missions', scope: 'page', route: '/missions' },
  { id: 'leaderboard', label: 'Leaderboard', scope: 'page', route: '/leaderboard' },
  { id: 'profile', label: 'Profile', scope: 'page', route: '/profile' },
  { id: 'assets', label: 'Assets', scope: 'assets' },
]

/** "titleBrand" → "Title Brand", "bg2" → "Bg2". */
function humanize(seg: string): string {
  return seg.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/^./, (c) => c.toUpperCase())
}

const CONTENT_GROUP: Record<keyof ContentMap, string> = {
  brand: 'brand',
  nav: 'nav',
  footer: 'footer',
  onboarding: 'onboarding',
  leaderboard: 'leaderboard',
  profile: 'profile',
  missions: 'missions',
}

function leafEntries(obj: unknown, prefix: string): { path: string; isArray: boolean }[] {
  if (obj === null || typeof obj !== 'object' || Array.isArray(obj)) {
    return [{ path: prefix, isArray: Array.isArray(obj) }]
  }
  return Object.entries(obj as Record<string, unknown>).flatMap(([k, v]) =>
    leafEntries(v, prefix ? `${prefix}.${k}` : k)
  )
}

function contentFields(): FieldDef[] {
  return leafEntries(DEFAULT_CONTENT, 'content').map(({ path, isArray }) => {
    const parts = path.split('.')
    const ns = parts[1] as keyof ContentMap
    const leaf = parts[parts.length - 1]
    const kind: FieldKind = isArray ? 'list' : leaf === 'body' ? 'textarea' : 'text'
    return { path, label: humanize(leaf), kind, group: CONTENT_GROUP[ns] }
  })
}

const C = (slots: string[]) => slots.map((s) => ({ slot: s, kind: 'color' as FieldKind }))

interface RecipeSpec {
  recipe: string
  group: string
  fields: {
    slot: string
    kind: FieldKind
    options?: string[]
    min?: number
    max?: number
    step?: number
  }[]
}

const RECIPES: RecipeSpec[] = [
  {
    recipe: 'missionCard',
    group: 'missions',
    fields: [
      ...C(['panel', 'panel2', 'border', 'title', 'body', 'iconBoxBg', 'iconBoxBorder', 'ctaFg']),
      { slot: 'haloOpacity', kind: 'range', min: 0, max: 1, step: 0.01 },
    ],
  },
  {
    recipe: 'missionModal',
    group: 'missions',
    fields: C([
      'panel',
      'panel2',
      'border',
      'title',
      'body',
      'backdrop',
      'headerBorder',
      'closeBg',
      'closeBorder',
      'closeIcon',
    ]),
  },
  {
    recipe: 'rewardCard',
    group: 'missions',
    fields: C(['panel', 'panel2', 'border', 'title', 'body', 'imageArea', 'imageAreaBorder']),
  },
  {
    recipe: 'heroBanner',
    group: 'missions',
    fields: [
      ...C(['panel', 'border']),
      { slot: 'overlayGradient', kind: 'text' },
      { slot: 'overlayMode', kind: 'select', options: ['always', 'eyebrow-only', 'never'] },
    ],
  },
  {
    recipe: 'onboardingCard',
    group: 'onboarding',
    fields: C([
      'panel',
      'panel2',
      'border',
      'title',
      'body',
      'heroBg',
      'formBg',
      'statTileBg',
      'statTileBorder',
      'brandEmphasis',
      'linkColor',
    ]),
  },
  {
    recipe: 'leaderboardRow',
    group: 'leaderboard',
    fields: [
      ...C(['rowPanel', 'rowBorder', 'headPanel', 'headText', 'mineHighlight', 'topRankColor']),
      { slot: 'tierTones', kind: 'toneMap' },
    ],
  },
  {
    recipe: 'podium',
    group: 'leaderboard',
    fields: [
      { slot: 'rankColors.1', kind: 'color' },
      { slot: 'rankColors.2', kind: 'color' },
      { slot: 'rankColors.3', kind: 'color' },
      { slot: 'platformHeights.1', kind: 'number', min: 0, max: 400 },
      { slot: 'platformHeights.2', kind: 'number', min: 0, max: 400 },
      { slot: 'platformHeights.3', kind: 'number', min: 0, max: 400 },
    ],
  },
  {
    recipe: 'profileCard',
    group: 'profile',
    fields: C([
      'panel',
      'panel2',
      'border',
      'title',
      'body',
      'statBg',
      'statBorder',
      'walletColor',
    ]),
  },
  {
    recipe: 'tierLadder',
    group: 'profile',
    fields: [
      { slot: 'currentMixPercent', kind: 'range', min: 0, max: 100, step: 1 },
      { slot: 'lockedOpacity', kind: 'range', min: 0, max: 1, step: 0.05 },
      ...C(['panel', 'panelCurrent']),
    ],
  },
  {
    recipe: 'badgeGrid',
    group: 'profile',
    fields: [...C(['panel', 'border', 'lockedFg']), { slot: 'unlockedTones', kind: 'list' }],
  },
  {
    recipe: 'statCard',
    group: 'profile',
    fields: C(['trendDefault', 'trendStreak', 'trendRewards']),
  },
  { recipe: 'xpChart', group: 'profile', fields: C(['gradientFrom', 'gradientTo']) },
  {
    recipe: 'topNav',
    group: 'nav',
    fields: C(['panel', 'border', 'linkColor', 'linkColorActive', 'linkBgActive']),
  },
  { recipe: 'footer', group: 'footer', fields: C(['panel', 'border', 'textColor', 'brandColor']) },
]

function recipeFields(): FieldDef[] {
  return RECIPES.flatMap((r) =>
    r.fields.map((f) => ({
      path: `overrides.${r.recipe}.${f.slot}`,
      label: f.slot.split('.').map(humanize).join(' '),
      kind: f.kind,
      group: r.group,
      options: f.options,
      min: f.min,
      max: f.max,
      step: f.step,
    }))
  )
}

function buildFields(): FieldDef[] {
  const out: FieldDef[] = []
  out.push({ path: 'mode', label: 'Mode', kind: 'mode', group: 'theme' })
  out.push({ path: 'brand.primary', label: 'Primary', kind: 'color', group: 'brand' })
  out.push({ path: 'brand.secondary', label: 'Secondary', kind: 'color', group: 'brand' })
  out.push(...contentFields())
  for (const key of Object.keys(PALETTES.dark)) {
    out.push({
      path: `overrides.palette.${key}`,
      label: humanize(key),
      kind: 'color',
      group: 'palette',
    })
  }
  for (const r of ['card', 'button', 'tag', 'modal']) {
    out.push({
      path: `overrides.radius.${r}`,
      label: `Radius ${humanize(r)}`,
      kind: 'text',
      group: 'shape',
    })
  }
  for (const f of ['display', 'ui', 'mono']) {
    out.push({
      path: `overrides.fonts.${f}`,
      label: `Font ${humanize(f)}`,
      kind: 'text',
      group: 'shape',
    })
  }
  out.push(...recipeFields())
  out.push({
    path: 'assets.onboardingHero',
    label: 'Onboarding hero',
    kind: 'asset',
    group: 'assets',
  })
  out.push({ path: 'assets.missionsHero', label: 'Missions hero', kind: 'asset', group: 'assets' })
  return out
}

export const FIELDS: readonly FieldDef[] = buildFields()

export function fieldsForGroup(groupId: string): FieldDef[] {
  return FIELDS.filter((f) => f.group === groupId)
}
