import type { Mission, LeaderboardEntry, Reward, Badge, Tier } from './types'

// Stable module-level timestamp so limited missions don't get a new deadline on every render.
const LAUNCH_EVENT_ENDS = Date.now() + 3600 * 1000 * 26

export const MISSIONS: Mission[] = [
  {
    id: 'mev1',
    type: 'verify_email',
    title: 'Verify your email',
    desc: 'Confirm your address with a 6-digit code to claim XP.',
    xp: 80,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'mav1',
    type: 'avatar',
    title: 'Upload your profile picture',
    desc: 'Add a face to your handle — drag in a photo to claim XP.',
    xp: 120,
    progress: [0, 1],
    tone: 'secondary',
  },

  {
    id: 'm1',
    type: 'social',
    title: 'Follow GrowQuest on X',
    desc: 'Tap follow and never miss a drop.',
    xp: 150,
    progress: [0, 1],
    tone: 'primary',
    url: 'https://x.com',
  },
  {
    id: 'm2',
    type: 'photo',
    title: 'Share your quest moment',
    desc: 'Upload a photo using #GrowQuestLive.',
    xp: 250,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'm3',
    type: 'refer',
    title: 'Invite 3 teammates',
    desc: 'Refer friends and earn bonus XP on each signup.',
    xp: 450,
    progress: [1, 3],
    tone: 'primary',
  },
  {
    id: 'm4',
    type: 'video',
    title: 'Watch the onboarding film',
    desc: '90 seconds on how GrowQuest works.',
    xp: 100,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'mq1',
    type: 'quiz',
    subtype: 'quiz-text',
    title: 'Quick quiz · text answers',
    desc: '1 question, 4 text choices. Nail it for XP.',
    xp: 150,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'mq2',
    type: 'quiz',
    subtype: 'quiz-textImage',
    title: 'Visual quiz · text + image',
    desc: 'Pick the right layout from 4 visual options.',
    xp: 200,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'mq3',
    type: 'quiz',
    subtype: 'quiz-imageOnly',
    title: 'Brand quiz · image-only',
    desc: 'Identify the correct mark. No words.',
    xp: 220,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'ms1',
    type: 'survey',
    subtype: 'survey-text',
    title: 'Survey · which feature wins?',
    desc: 'One question, your voice shapes the roadmap.',
    xp: 120,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'ms2',
    type: 'survey',
    subtype: 'survey-textImage',
    title: 'Survey · pick your vibe',
    desc: 'Text + image options. 15 seconds.',
    xp: 140,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'ms3',
    type: 'survey',
    subtype: 'survey-imageOnly',
    title: 'Survey · vibe check (visual)',
    desc: 'Pick the shape that speaks to you.',
    xp: 140,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'ms4',
    type: 'survey',
    subtype: 'survey-textarea',
    title: 'Founder interview · open answer',
    desc: 'Tell us your biggest growth pain. 20+ chars.',
    xp: 400,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'mg1',
    type: 'hangman',
    title: 'Hangman: guess the word',
    desc: '6 lives. Figure out the GrowQuest word.',
    xp: 300,
    progress: [0, 1],
    tone: 'primary',
  },
  {
    id: 'mg2',
    type: 'trivia',
    title: 'Rapid-fire trivia',
    desc: '3 questions · 15s each · score 2+ to pass.',
    xp: 350,
    progress: [0, 3],
    tone: 'primary',
  },
  {
    id: 'm6',
    type: 'review',
    title: 'Leave a review',
    desc: 'Rate your experience on G2 or Capterra.',
    xp: 300,
    progress: [0, 1],
    tone: 'secondary',
  },
  {
    id: 'm7',
    type: 'event',
    title: 'RSVP: Launch showcase',
    desc: 'Live demo + lootbox drop — Thursday 4pm PT.',
    xp: 180,
    progress: [0, 1],
    tone: 'primary',
    limited: true,
    endsAt: LAUNCH_EVENT_ENDS,
  },
  {
    id: 'm8',
    type: 'purchase',
    title: 'Complete your first order',
    desc: "Unlock the founders' tier.",
    xp: 600,
    progress: [0, 1],
    tone: 'primary',
  },
]

export const LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, handle: '@northstar', xp: 18420, streak: 47, tier: 'Oracle', me: false, seed: 2 },
  { rank: 2, handle: '@kodex', xp: 16100, streak: 23, tier: 'Oracle', me: false, seed: 4 },
  { rank: 3, handle: '@lunalabs', xp: 14280, streak: 31, tier: 'Ascendant', me: false, seed: 1 },
  { rank: 4, handle: '@you', xp: 9840, streak: 12, tier: 'Voyager', me: true, seed: 7 },
  { rank: 5, handle: '@harbor', xp: 8610, streak: 9, tier: 'Voyager', me: false, seed: 3 },
  { rank: 6, handle: '@vektor', xp: 7420, streak: 14, tier: 'Voyager', me: false, seed: 5 },
  { rank: 7, handle: '@minteo', xp: 6180, streak: 6, tier: 'Scout', me: false, seed: 6 },
  { rank: 8, handle: '@quill', xp: 5720, streak: 3, tier: 'Scout', me: false, seed: 8 },
]

export const REWARDS: Reward[] = [
  {
    id: 'r1',
    title: "Founders' hoodie",
    cost: 4500,
    stock: 'In stock',
    tone: 'primary',
    kind: 'merch',
    imageUrl: 'https://cdn.grow-quest.com/tshirt.jpeg',
  },
  {
    id: 'r2',
    title: '1-year Pro license',
    cost: 8000,
    stock: '12 left',
    tone: 'secondary',
    kind: 'digital',
  },
  {
    id: 'r3',
    title: 'Priority Slack channel',
    cost: 2400,
    stock: 'In stock',
    tone: 'primary',
    kind: 'access',
  },
  {
    id: 'r4',
    title: 'Private beta keys (×3)',
    cost: 1800,
    stock: '28 left',
    tone: 'secondary',
    kind: 'digital',
  },
  {
    id: 'r5',
    title: 'Co-brand Zoom background kit',
    cost: 500,
    stock: 'In stock',
    tone: 'primary',
    kind: 'digital',
  },
  {
    id: 'r6',
    title: 'Dinner with the founders',
    cost: 12000,
    stock: 'Limited drop',
    tone: 'secondary',
    kind: 'experience',
    limited: true,
    imageUrl: 'https://cdn.grow-quest.com/dinner.jpeg',
  },
]

export const BADGES: Badge[] = [
  { id: 'b1', name: 'First Quest', got: true, desc: 'Completed your first mission.' },
  { id: 'b2', name: 'Streak x7', got: true, desc: '7-day streak maintained.' },
  { id: 'b3', name: 'Insider', got: true, desc: 'Reached Voyager tier.' },
  { id: 'b4', name: 'Evangelist', got: false, desc: 'Refer 10 teammates.' },
  { id: 'b5', name: 'Lorekeeper', got: false, desc: 'Complete all weekly quizzes in a month.' },
  { id: 'b6', name: "Founder's Cut", got: false, desc: 'Reach Oracle tier.' },
]

export const TIERS: Tier[] = [
  { name: 'Scout', min: 0, color: 'var(--ink-dim)' },
  { name: 'Voyager', min: 5000, color: 'var(--color-primary)' },
  {
    name: 'Ascendant',
    min: 12000,
    color: 'color-mix(in oklch, var(--color-primary) 50%, var(--color-secondary))',
  },
  { name: 'Oracle', min: 25000, color: 'var(--color-secondary)' },
]
